//! The hand-rolled BERT **pair** encoder and the Rust ONNX path, checked against the real ones.
//!
//! `tests/fixtures/cross-encoder-reference*.json` is generated by
//! `tools/make_cross_encoder_fixtures.py` from HuggingFace `tokenizers` and ONNX Runtime, on a
//! digest-pinned graph and its `tokenizer.json`. **It is never regenerated to make this test
//! pass.** If Rust disagrees, Rust is wrong until proven otherwise — the rule `eval/` lives
//! under, applied one layer down. This is STATE.md's standing check:
//!
//! > A second implementation of a scored-path component must reproduce the first on unmodified
//! > input.
//!
//! Two layers are checked and the first is the one that matters. **Token ids are checked exactly**,
//! because they are integers and there is no such thing as a close token id — a single wrong id is
//! a different input to the graph, and the graph will still return a plausible score. **Logits are
//! checked against a stated tolerance**, because they are floats crossing an FFI boundary into a
//! quantized graph.
//!
//! The case that earns this test is `long query AND long document`. HuggingFace truncates pairs
//! with `longest_first` — dropping one token at a time from whichever sequence is currently longer
//! — and an implementation that instead truncated only the document would match every other case
//! in the fixture and fail that one.
//!
//! ## Two graphs, and the second one is why this is a table — Session K
//!
//! The tokenizer half runs against **every** fixture present, because the fine-tune ships a
//! *different* `tokenizer.json` than the Xenova export it descends from. The two are byte-identical
//! in `vocab`, `normalizer`, `pre_tokenizer`, `post_processor` and `decoder`, and differ only in
//! embedded `padding`/`truncation` blocks that this crate implements itself — so the ids *should*
//! agree, and this file is where "should" becomes "does".
//!
//! The graph half runs against whichever fixtures have their model present. `models/` is gitignored,
//! so a fresh clone has neither and skips both; a developer with only the shipped graph checks the
//! shipped graph. **Only the shipped graph's fixture is load-bearing for the running binary** — the
//! int8 entry is Session H's record, kept so a regression in the pair encoder is caught on both
//! vocabularies rather than only the current one.

use std::path::{Path, PathBuf};

use marlowe_memory::cue::dense::tokenizer::{encode_pair, Vocab};
use marlowe_memory::rerank::{CrossEncoder, BATCH, MAX_SEQ_LEN, MODEL_FILE, TOKENIZER_FILE};

/// Absolute tolerance on one logit, and the reason it is not zero.
///
/// The reference runs ONNX Runtime through Python; this runs the same graph through `ort`'s
/// statically linked build of the same pinned 1.22.0. Identical weights and identical input ids,
/// but not necessarily an identical arena or thread pool, so bit equality is not something to
/// demand across the boundary.
///
/// **1e-3 is small relative to the quantity that matters.** These logits span roughly −12 to +8 in
/// the fixture, and the int8 batch-invariance failure Session G measured — the thing this stage is
/// built to avoid — was 0.037, more than an order of magnitude larger. So a drift this test would
/// tolerate cannot hide the failure mode the batch-1 design exists to prevent.
const LOGIT_TOLERANCE: f32 = 1e-3;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/marlowe-memory -> repo root")
        .to_path_buf()
}

/// One `(model directory, graph file, fixture)` triple.
///
/// `graph_file` is carried explicitly rather than read from [`MODEL_FILE`]: the superseded entry's
/// graph is `model_int8.onnx` and the shipped one's is `model.onnx`, and a table that assumed the
/// current constant would silently stop checking the other row.
struct Reference {
    dir: &'static str,
    graph_file: &'static str,
    fixture: &'static str,
    /// True for the graph `CrossEncoder::load` is pinned to. Only this row can exercise the ONNX
    /// path — `load` refuses everything else by digest, which is the point of the pin.
    shipped: bool,
}

const REFERENCES: &[Reference] = &[
    Reference {
        dir: "ms-marco-MiniLM-L-2-v2-ft-session-j",
        graph_file: MODEL_FILE,
        fixture: "cross-encoder-reference-ft-session-j.json",
        shipped: true,
    },
    // Session H's record. The pair encoder must reproduce HuggingFace on this vocabulary too; the
    // graph is no longer loadable through `CrossEncoder` and is not expected to be.
    Reference {
        dir: "ms-marco-MiniLM-L-2-v2-int8",
        graph_file: "model_int8.onnx",
        fixture: "cross-encoder-reference.json",
        shipped: false,
    },
];

fn model_dir(r: &Reference) -> PathBuf {
    repo_root().join("models").join(r.dir)
}

fn fixture(r: &Reference) -> serde_json::Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(r.fixture);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{} is missing ({e}). Regenerate with `python tools/make_cross_encoder_fixtures.py \
             --model-dir models/{} --model-file {} --out crates/marlowe-memory/tests/fixtures/{}`",
            path.display(),
            r.dir,
            r.graph_file,
            r.fixture
        )
    });
    serde_json::from_str(&text).expect("fixture parses")
}

fn shipped() -> &'static Reference {
    REFERENCES.iter().find(|r| r.shipped).expect("exactly one shipped reference")
}

/// Load the vocabulary, or explain precisely why the test cannot run.
///
/// **Skips when the model is absent, and that is right here for the same reason it is right in
/// `embedding_reference.rs`:** `models/` is gitignored and never vendored, so a fresh clone
/// legitimately does not have it, and failing would mean `cargo test` could not pass on a clean
/// checkout while saying nothing about the code.
///
/// It does **not** skip when the file is present and wrong. A digest or size mismatch is a real
/// disagreement, and `CrossEncoder::load` refuses it.
fn vocab_or_skip(r: &Reference) -> Option<Vocab> {
    let path = model_dir(r).join(TOKENIZER_FILE);
    if !path.exists() {
        eprintln!(
            "SKIP: {} is absent. models/ is gitignored; see runs/session-j/finetuned-manifest.json \
             for the shipped graph's pinned digests.",
            path.display()
        );
        return None;
    }
    let text = std::fs::read_to_string(&path).expect("tokenizer.json reads");
    Some(Vocab::from_tokenizer_json(&text, &path.display().to_string()).expect("tokenizer.json parses"))
}

fn u32s(value: &serde_json::Value, key: &str) -> Vec<u32> {
    value[key]
        .as_array()
        .unwrap_or_else(|| panic!("fixture case has no {key:?}"))
        .iter()
        .map(|v| v.as_u64().expect("id is an integer") as u32)
        .collect()
}

#[test]
fn the_pair_encoder_reproduces_huggingface_exactly() {
    let mut checked = 0usize;
    for r in REFERENCES {
        let Some(vocab) = vocab_or_skip(r) else { continue };
        let fx = fixture(r);
        assert_eq!(
            fx["max_seq_len"].as_u64().unwrap() as usize,
            MAX_SEQ_LEN,
            "{}: the fixture was generated at a different sequence length than this build uses",
            r.dir
        );

        for case in fx["cases"].as_array().expect("cases") {
            let name = case["name"].as_str().unwrap();
            let query = case["query"].as_str().unwrap();
            let document = case["document"].as_str().unwrap();

            let got = encode_pair(&vocab, query, document, MAX_SEQ_LEN);
            let at = format!("{} / {name:?}", r.dir);

            // Exact. There is no tolerance on an integer.
            assert_eq!(got.input_ids, u32s(case, "input_ids"), "input_ids differ on {at}");
            assert_eq!(
                got.attention_mask,
                u32s(case, "attention_mask"),
                "attention_mask differs on {at}"
            );
            assert_eq!(
                got.token_type_ids,
                u32s(case, "token_type_ids"),
                "token_type_ids differ on {at} -- this is the input carrying the query/document \
                 boundary, and a graph fed the wrong one still returns a plausible score"
            );
            assert_eq!(
                got.truncated,
                case["truncated"].as_bool().unwrap(),
                "truncation flag differs on {at}"
            );
            assert_eq!(got.input_ids.len(), MAX_SEQ_LEN, "padded to a fixed shape on {at}");
        }
        checked += 1;
    }
    eprintln!("pair encoder checked against {checked} of {} vocabularies", REFERENCES.len());
}

#[test]
fn the_two_vocabularies_encode_identically() {
    // The fine-tune ships a DIFFERENT tokenizer.json than the Xenova export it descends from.
    // `rerank.rs` claims the difference is inert -- padding/truncation blocks this crate does not
    // read -- and that claim is load-bearing for reusing one pair encoder across both. Asserted
    // here rather than left in a doc comment.
    let (Some(a), Some(b)) = (vocab_or_skip(&REFERENCES[0]), vocab_or_skip(&REFERENCES[1])) else {
        eprintln!("SKIP: both model directories are needed to compare vocabularies");
        return;
    };
    for case in fixture(shipped())["cases"].as_array().expect("cases") {
        let (q, d) = (case["query"].as_str().unwrap(), case["document"].as_str().unwrap());
        let ea = encode_pair(&a, q, d, MAX_SEQ_LEN);
        let eb = encode_pair(&b, q, d, MAX_SEQ_LEN);
        assert_eq!(ea.input_ids, eb.input_ids, "ids diverge on {:?}", case["name"]);
        assert_eq!(ea.token_type_ids, eb.token_type_ids, "types diverge on {:?}", case["name"]);
    }
}

#[test]
fn the_longest_first_case_actually_exercises_the_strategy() {
    // A guard on the FIXTURE, not on the code. The `long query AND long document` case only
    // discriminates `longest_first` from "truncate the document" while both sequences are long
    // enough to compete for the budget. If someone shortened those strings, every assertion above
    // would still pass and the test would silently stop checking the thing it exists for.
    let Some(vocab) = vocab_or_skip(shipped()) else { return };
    let fx = fixture(shipped());
    let case = fx["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == "long query AND long document")
        .expect("the longest_first case is present");

    let query = case["query"].as_str().unwrap();
    let document = case["document"].as_str().unwrap();
    let types = u32s(case, "token_type_ids");

    let segment_a = types.iter().take_while(|&&t| t == 0).count();
    let segment_b = types.iter().filter(|&&t| t == 1).count();
    assert!(
        segment_a > 10 && segment_b > 10,
        "both segments must survive truncation for this case to discriminate longest_first; \
         got a={segment_a} b={segment_b}"
    );

    // And the naive strategy really would differ: truncating only the document would leave the
    // full query in segment A.
    let full_query = encode_pair(&vocab, query, "", MAX_SEQ_LEN);
    let full_query_len = full_query.token_type_ids.iter().take_while(|&&t| t == 0).count();
    assert_ne!(
        segment_a, full_query_len,
        "the query was NOT truncated, so this case does not distinguish longest_first from \
         document-only truncation"
    );
    let _ = document;
}

#[test]
fn the_rust_graph_reproduces_the_reference_logits() {
    let r = shipped();
    if !model_dir(r).join(MODEL_FILE).exists() {
        eprintln!("SKIP: {} is absent.", model_dir(r).join(MODEL_FILE).display());
        return;
    }
    let fx = fixture(r);
    let mut encoder = CrossEncoder::load(&model_dir(r)).expect("the pinned cross-encoder loads");

    for case in fx["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().unwrap();
        let expected = case["logit"].as_f64().unwrap() as f32;
        let got = encoder
            .score(case["query"].as_str().unwrap(), case["document"].as_str().unwrap())
            .expect("scoring succeeds");
        assert!(
            (got - expected).abs() <= LOGIT_TOLERANCE,
            "{name:?}: Rust {got} vs reference {expected}, difference {} exceeds {LOGIT_TOLERANCE}",
            (got - expected).abs()
        );
    }
}

#[test]
fn scoring_the_same_pair_twice_gives_the_same_logit() {
    // `repro --runs 2` is the standing check that would catch a batch-invariance regression at the
    // suite level. This is the same property asserted at the unit level, where a failure names the
    // stage instead of surfacing as two different run hashes.
    let r = shipped();
    if !model_dir(r).join(MODEL_FILE).exists() {
        return;
    }
    let mut encoder = CrossEncoder::load(&model_dir(r)).expect("loads");
    let q = "which database did the analytics warehouse move to";
    let d = "I moved the analytics warehouse off Postgres in April after the ingest job timed out.";
    let a = encoder.score(q, d).expect("scores");
    let b = encoder.score(q, d).expect("scores");
    assert_eq!(a.to_bits(), b.to_bits(), "bit-identical, not merely close");
}

#[test]
fn the_batch_dimension_is_one_and_there_is_no_way_to_raise_it() {
    // The structural half of the batch-invariance defence. `BATCH` is a constant, `score` takes a
    // single pair, and there is no slice-taking entry point on `CrossEncoder` -- so reintroducing
    // batching requires changing a signature, not passing a bigger argument.
    //
    // The shipped f32 graph IS batch-invariant, at 0.000000. Batch 1 is kept anyway because
    // invariance is a per-graph measurement that is never inherited by the next re-pin. See
    // rerank.rs module docs.
    assert_eq!(BATCH, 1, "batch is fixed at 1 structurally; see rerank.rs module docs");
}

#[test]
fn the_superseded_int8_directory_is_refused_by_name() {
    // A stale `--reranking` path is the most likely way this stage gets loaded wrong, and the
    // failure has to name ADR-018 rather than read as a missing download. Skips when the old
    // directory is absent -- models/ is gitignored and nothing requires keeping it.
    let old = repo_root().join("models").join("ms-marco-MiniLM-L-2-v2-int8");
    if !old.join("model_int8.onnx").exists() {
        eprintln!("SKIP: the superseded int8 directory is absent.");
        return;
    }
    // `CrossEncoder` holds an `ort::Session` and is deliberately not `Debug`, so match rather
    // than `expect_err`.
    let text = match CrossEncoder::load(&old) {
        Ok(_) => panic!("the pre-Session-K int8 graph loaded; the pin is not doing its job"),
        Err(e) => e.to_string(),
    };
    assert!(
        text.contains("Session J fine-tune") && text.contains("ADR-018"),
        "the refusal must say what happened, not just that a file is missing. Got: {text}"
    );
}
