//! The hand-rolled tokenizer, checked against HuggingFace's own output.
//!
//! `tests/fixtures/wordpiece-reference.json` is generated by `tools/make_embedding_fixtures.py`
//! from HuggingFace's `BertTokenizer`, built on the pinned `vocab.txt` and
//! `tokenizer_config.json`. **It is never regenerated to make this test pass.** If Rust
//! disagrees, Rust is wrong until proven otherwise — the rule `eval/` lives under, applied one
//! layer down.
//!
//! This is the test that makes two things safe: a hand-rolled tokenizer, and a dependency on
//! Unicode tables whose contents are versioned. Either could drift silently and either would
//! surface, weeks later, as `marlowe-eval repro` producing two different sha256 with nothing
//! pointing at the cause. Here it fails by name, on the case that broke, with the expected and
//! actual token strings printed.
//!
//! **There is no tolerance on an integer**, and there is one on a float. The tokenizer checks
//! below demand exact equality; the embedder checks at the bottom of this file state a tolerance
//! and justify it against a measured floor. Both strictnesses are deliberate and neither is a
//! default.

use std::path::{Path, PathBuf};

use marlowe_memory::cue::dense::tokenizer::{encode, Vocab, VOCAB_SIZE};
use marlowe_memory::cue::dense::MAX_SEQ_LEN;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/marlowe-memory -> repo root")
        .to_path_buf()
}

fn model_dir() -> PathBuf {
    repo_root().join("models").join("jina-embeddings-v2-small-en")
}

/// The fixture, parsed with `serde_json::Value` rather than a typed struct.
///
/// Deliberate: a typed struct with `#[serde(default)]` anywhere would let a fixture that lost a
/// field still deserialize, and the test would silently check less than it claims to.
fn fixture(name: &str) -> serde_json::Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures").join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} is missing ({e}). Regenerate with `python tools/make_embedding_fixtures.py`", path.display()));
    serde_json::from_str(&text).expect("fixture parses")
}

/// Load the pinned vocabulary, or explain precisely why the test cannot run.
///
/// **Skips rather than fails when the model is absent, and this is the one place that is
/// right.** `models/` is gitignored and never vendored, so a fresh clone legitimately does not
/// have it; failing here would mean `cargo test` could not pass on a clean checkout and the
/// failure would say nothing about the code. The skip prints the fetch command.
///
/// It does NOT skip when the model is present and wrong — a digest or size mismatch is a hard
/// failure, because that is a real disagreement rather than an absence.
fn vocab_or_skip() -> Option<Vocab> {
    let path = model_dir().join("vocab.txt");
    if !path.exists() {
        eprintln!(
            "SKIP: {} not found. Run `python tools/fetch_model.py` to enable this test. \
             models/ is gitignored and never vendored, so a fresh clone does not have it.",
            path.display()
        );
        return None;
    }
    let text = std::fs::read_to_string(&path).expect("vocab.txt reads");
    let vocab = Vocab::parse(&text, &path.display().to_string())
        .expect("the pinned vocab.txt must parse; a mismatch here is corruption, not absence");
    assert_eq!(vocab.len(), VOCAB_SIZE);
    Some(vocab)
}

#[test]
fn the_tokenizer_reproduces_huggingface_exactly() {
    let Some(vocab) = vocab_or_skip() else { return };
    let data = fixture("wordpiece-reference.json");

    let fixture_max = data["max_seq_len"].as_u64().expect("max_seq_len") as usize;
    assert_eq!(
        fixture_max, MAX_SEQ_LEN,
        "the fixture was generated at max_seq_len {fixture_max} but this build uses \
         {MAX_SEQ_LEN}. Every truncated case would disagree for a reason that has nothing to \
         do with the tokenizer. Regenerate the fixture deliberately, and expect the fitted \
         gate to be invalid until it is re-fit."
    );

    let cases = data["cases"].as_array().expect("cases");
    assert!(cases.len() >= 30, "the hazard set should not have shrunk: {}", cases.len());

    let mut failures = Vec::new();
    for case in cases {
        let text = case["text"].as_str().expect("text");
        let expected: Vec<u32> = case["input_ids"]
            .as_array()
            .expect("input_ids")
            .iter()
            .map(|v| v.as_u64().expect("id") as u32)
            .collect();

        let actual = encode(&vocab, text, MAX_SEQ_LEN);
        if actual.input_ids != expected {
            let expected_tokens: Vec<&str> = case["tokens"]
                .as_array()
                .expect("tokens")
                .iter()
                .map(|v| v.as_str().unwrap_or("?"))
                .collect();
            failures.push(format!(
                "text {text:?}\n      expected {expected:?}\n        ({expected_tokens:?})\n      \
                 actual   {:?}",
                actual.input_ids
            ));
        }

        assert_eq!(
            actual.attention_mask.len(),
            actual.input_ids.len(),
            "the mask must cover every token: the pooling divides by its sum"
        );
        assert!(
            actual.input_ids.len() <= MAX_SEQ_LEN,
            "text {text:?} produced {} ids, over the limit",
            actual.input_ids.len()
        );
    }

    assert!(
        failures.is_empty(),
        "{} of {} cases disagree with HuggingFace. The fixture is the authority; do NOT \
         regenerate it to make this pass:\n\n  {}",
        failures.len(),
        cases.len(),
        failures.join("\n\n  ")
    );
}

#[test]
fn truncation_matches_huggingface_including_which_cases_truncate() {
    // Not implied by the id check: a case could carry the right ids and disagree about whether
    // it was cut, and `truncated` is what the corpus-level truncation rate is built from.
    let Some(vocab) = vocab_or_skip() else { return };
    let data = fixture("wordpiece-reference.json");

    let mut checked = 0;
    for case in data["cases"].as_array().expect("cases") {
        let text = case["text"].as_str().expect("text");
        let expected = case["truncated"].as_bool().expect("truncated");
        let actual = encode(&vocab, text, MAX_SEQ_LEN);
        assert_eq!(actual.truncated, expected, "truncation flag for {text:?}");
        if expected {
            assert_eq!(actual.input_ids.len(), MAX_SEQ_LEN);
            checked += 1;
        }
    }
    assert!(checked > 0, "the hazard set must contain a case that actually truncates");
}

#[test]
fn a_vocabulary_of_the_wrong_size_is_refused_rather_than_used() {
    // The hazard: a different BERT vocabulary parses perfectly and produces ids the embedding
    // matrix was never trained on. The model still returns a plausible 384-dim vector.
    let short = (0..100).map(|i| format!("tok{i}")).collect::<Vec<_>>().join("\n");
    let err = Vocab::parse(&short, "fake.txt").unwrap_err();
    // Against the constant, not a literal: a hardcoded size here would have to be edited on
    // every model change, and the edit is exactly the moment someone stops reading the test.
    assert!(err.to_string().contains(&VOCAB_SIZE.to_string()), "{err}");
}

#[test]
fn a_vocabulary_missing_a_special_token_is_refused() {
    let mut lines: Vec<String> = (0..VOCAB_SIZE).map(|i| format!("tok{i}")).collect();
    lines[0] = "[UNK]".into();
    lines[1] = "[CLS]".into();
    // no [SEP]
    let err = Vocab::parse(&lines.join("\n"), "fake.txt").unwrap_err();
    assert!(err.to_string().contains("[SEP]"), "{err}");
}

#[test]
fn a_crlf_checkout_does_not_shift_every_token_id() {
    // vocab.txt is a text file in a gitignored directory a user fetched themselves. If a \r
    // survived into the token strings, every lookup would miss and every text would become
    // [UNK] -- which still embeds, still scores, and still ranks.
    let mut lines: Vec<String> = (0..VOCAB_SIZE).map(|i| format!("tok{i}")).collect();
    for (index, token) in ["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"].iter().enumerate() {
        lines[index] = (*token).to_string();
    }
    lines[5] = "hello".into();

    let unix = Vocab::parse(&lines.join("\n"), "fake.txt").expect("LF parses");
    let windows = Vocab::parse(&lines.join("\r\n"), "fake.txt").expect("CRLF parses");
    assert_eq!(unix.id("hello"), windows.id("hello"));
    assert_eq!(windows.id("hello"), Some(5));
}

// ----------------------------------------------------------------- the embedding itself

use marlowe_memory::cue::dense::embedder::{Embedder, MODEL_FILE};
use marlowe_memory::cue::dense::{cosine, DIMENSIONS};

/// **Cross-implementation, so it carries a tolerance — and the tolerance is measured, not
/// picked.** `tools/make_embedding_fixtures.py` records
/// `pooling_cross_check_vs_maintainer_graph`: the gap between our pooling recipe and the same
/// pooling compiled into the graph by the model's authors, ~1.1e-7. A Rust-vs-reference
/// tolerance tighter than the gap between two faithful implementations would fail an
/// implementation for being correct.
///
/// 1e-4 leaves three orders of magnitude of headroom over that floor, which is deliberate: the
/// reference runs ONNX Runtime 1.24.2 (Python) and this build links 1.22.0, and that version
/// difference alone measures ~2.75e-6.
///
/// Contrast `the_tokenizer_reproduces_huggingface_exactly`, which has **no** tolerance. There is
/// none on an integer, and there is one here, and the difference is the point.
const MAX_ABS_DIFF: f32 = 1e-4;
const MIN_COSINE: f32 = 0.9999;

#[test]
fn the_embedder_reproduces_the_reference_within_a_measured_tolerance() {
    let dir = model_dir();
    if !dir.join(MODEL_FILE).exists() {
        eprintln!("SKIP: run `python tools/fetch_model.py`");
        return;
    }
    let data = fixture("embedding-reference.json");
    assert_eq!(data["dimensions"].as_u64().unwrap() as usize, DIMENSIONS);

    let mut embedder = match Embedder::load(&dir, 1, None) {
        Ok(e) => e,
        Err(e) => panic!("the pinned model must load: {e}"),
    };

    let mut worst_abs = 0.0f32;
    let mut worst_cos = 1.0f32;
    let mut worst_text = String::new();

    for case in data["cases"].as_array().expect("cases") {
        let text = case["text"].as_str().expect("text");
        let expected: Vec<f32> = case["embedding"]
            .as_array()
            .expect("embedding")
            .iter()
            .map(|v| v.as_f64().expect("f64") as f32)
            .collect();
        assert_eq!(expected.len(), DIMENSIONS);

        let actual = embedder.embed(text).expect("embeds");
        assert_eq!(actual.len(), DIMENSIONS);

        // Unit length is a property of the pooling, checked separately from agreement: a
        // systematically mis-scaled vector could still correlate perfectly with the reference.
        let norm = actual.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-4, "not unit length ({norm}) for {text:?}");

        let abs = actual
            .iter()
            .zip(&expected)
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        let cos = cosine(&actual, &expected);
        if abs > worst_abs {
            worst_abs = abs;
            worst_text = text.to_string();
        }
        worst_cos = worst_cos.min(cos);
    }

    println!("worst abs diff {worst_abs:.3e} on {worst_text:?}, min cosine {worst_cos:.8}");
    assert!(
        worst_abs <= MAX_ABS_DIFF,
        "max abs diff {worst_abs:.3e} exceeds {MAX_ABS_DIFF:.0e}, worst on {worst_text:?}. The \
         fixture is the authority; do NOT regenerate it to make this pass. Check the pooling, \
         the mask, and the normalization in that order"
    );
    assert!(worst_cos >= MIN_COSINE, "min cosine {worst_cos:.8} below {MIN_COSINE}");
}

#[test]
fn embedding_is_bit_identical_across_calls_and_worker_counts() {
    // The property `marlowe-eval repro` depends on. NO tolerance here -- this is Rust against
    // Rust, and the bit-identical claim's one-key allowlist (latency_ms) is not widened.
    let dir = model_dir();
    if !dir.join(MODEL_FILE).exists() {
        eprintln!("SKIP: run `python tools/fetch_model.py`");
        return;
    }
    let texts: Vec<String> = fixture("embedding-reference.json")["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .map(|c| c["text"].as_str().expect("text").to_string())
        .collect();

    let mut one = Embedder::load(&dir, 1, None).expect("loads");
    let first = one.embed_batch(&texts).expect("embeds");
    let second = one.embed_batch(&texts).expect("embeds");
    assert_eq!(first, second, "two calls in one process must agree bit for bit");

    for workers in [2usize, 8] {
        let mut many = Embedder::load(&dir, workers, None).expect("loads");
        let parallel = many.embed_batch(&texts).expect("embeds");
        assert_eq!(
            parallel, first,
            "worker count {workers} changed the output. Parallelism is supposed to be at the \
             TEXT level, so worker count cannot be a quality knob -- if this fails, it is"
        );
    }
}

#[test]
fn the_cache_returns_exactly_what_the_model_computed() {
    // STATE.md standing check, exercised against the REAL embedder rather than synthetic
    // vectors: ADR-004's model choice is conditional on this holding.
    let dir = model_dir();
    if !dir.join(MODEL_FILE).exists() {
        eprintln!("SKIP: run `python tools/fetch_model.py`");
        return;
    }
    let texts: Vec<String> = ["the ingest job times out", "we had pasta for dinner", ""]
        .iter()
        .map(|s| s.to_string())
        .collect();

    let cache_dir = std::env::temp_dir().join("marlowe-embedder-cache-roundtrip");
    let _ = std::fs::remove_dir_all(&cache_dir);

    let uncached = Embedder::load(&dir, 1, None)
        .expect("loads")
        .embed_batch(&texts)
        .expect("embeds");

    let mut cold = Embedder::load(&dir, 1, Some(&cache_dir)).expect("loads");
    let first = cold.embed_batch(&texts).expect("embeds");
    assert_eq!(first, uncached, "a cold cache must not change the vectors");
    assert_eq!(cold.cache_stats(), Some((0, texts.len() as u64)), "all misses");

    // A fresh process, warm cache: every vector must now come from disk, bit for bit.
    let mut warm = Embedder::load(&dir, 1, Some(&cache_dir)).expect("loads");
    let second = warm.embed_batch(&texts).expect("embeds");
    assert_eq!(warm.cache_stats(), Some((texts.len() as u64, 0)), "all hits");
    for (a, b) in second.iter().flatten().zip(uncached.iter().flatten()) {
        assert_eq!(a.to_bits(), b.to_bits(), "cache hit differs from the computed vector");
    }
}

