//! Which half of crossterm's Windows output path is live, and does colour survive it.
//!
//! This exists because a pipe and a console handle are different code paths on Windows, and the
//! difference is invisible from a redirected capture: `marlowe --tui | xxd` shows correct 24-bit
//! SGR while the same binary in Windows Terminal renders entirely achromatic. A probe that writes
//! through a pipe therefore cannot answer the question — it has to run in the real window.
//!
//! Three writers, same window, same frame:
//!   1. raw bytes, straight to stdout, bypassing crossterm entirely
//!   2. crossterm `SetForegroundColor`, executed
//!   3. crossterm `SetForegroundColor`, queued then flushed — which is what ratatui does
//!
//! If (1) is coloured and (2)/(3) are not, the WinAPI attribute path is active and the fix is to
//! force ANSI on before crossterm caches its answer.

use std::io::{self, Write};

use crossterm::style::{Color, Print, ResetColor, SetForegroundColor};
use crossterm::{execute, queue};

fn main() -> io::Result<()> {
    let mut out = io::stdout();

    println!();
    println!("  PROBE: crossterm from the marlowe binary's own dependency graph");
    println!();

    #[cfg(windows)]
    {
        println!("  supports_ansi()      {}", crossterm::ansi_support::supports_ansi());
        println!("  console mode         {}", console_mode_report());
    }

    // 1. Raw bytes. No crossterm. This is the control: it proved coloured in the PowerShell probe.
    write!(out, "  raw bytes            \x1b[38;2;155;126;222mACCENT 9B7EDE\x1b[0m  ")?;
    write!(out, "\x1b[38;2;255;0;0mRED\x1b[0m \x1b[35mMAGENTA-16\x1b[0m\n")?;
    out.flush()?;

    // 2. crossterm, executed immediately.
    write!(out, "  crossterm execute!   ")?;
    out.flush()?;
    execute!(
        out,
        SetForegroundColor(Color::Rgb { r: 155, g: 126, b: 222 }),
        Print("ACCENT 9B7EDE"),
        ResetColor,
        Print("  "),
        SetForegroundColor(Color::Magenta),
        Print("MAGENTA-16"),
        ResetColor,
        Print("\n"),
    )?;

    // 3. crossterm, queued then flushed. This is ratatui's CrosstermBackend, exactly.
    write!(out, "  crossterm queue!     ")?;
    queue!(
        out,
        SetForegroundColor(Color::Rgb { r: 155, g: 126, b: 222 }),
        Print("ACCENT 9B7EDE"),
        ResetColor,
        Print("  "),
        SetForegroundColor(Color::Magenta),
        Print("MAGENTA-16"),
        ResetColor,
        Print("\n"),
    )?;
    out.flush()?;

    // 4. The same commands into a Vec, printed back escaped. `supports_ansi()` is a process-wide
    //    answer, not a per-writer one, so this Vec takes whichever branch io::Stdout just took —
    //    which makes it a readout of what crossterm generated *in this console*, not in a pipe.
    let mut buf: Vec<u8> = Vec::new();
    queue!(
        buf,
        SetForegroundColor(Color::Rgb { r: 155, g: 126, b: 222 }),
        Print("X"),
        ResetColor,
    )?;
    write!(out, "  generated bytes      ")?;
    for b in &buf {
        match b {
            0x1b => write!(out, "<ESC>")?,
            0x20..=0x7e => write!(out, "{}", *b as char)?,
            _ => write!(out, "<{b:02X}>")?,
        }
    }
    writeln!(out, "   ({} bytes)", buf.len())?;
    out.flush()?;

    println!();
    println!("  If line 1 is coloured and lines 2-3 are not, crossterm is on the WinAPI path.");

    std::thread::sleep(std::time::Duration::from_secs(600));
    Ok(())
}

#[cfg(windows)]
fn console_mode_report() -> String {
    // Read it rather than assume it. `enable_raw_mode` succeeding says the call worked, not that
    // virtual-terminal processing is in force on the handle ratatui will write to.
    unsafe extern "system" {
        fn GetStdHandle(n: u32) -> isize;
        fn GetConsoleMode(h: isize, m: *mut u32) -> i32;
    }
    const STD_OUTPUT_HANDLE: u32 = -11i32 as u32;
    const ENABLE_VIRTUAL_TERMINAL_PROCESSING: u32 = 0x0004;
    let mut mode = 0u32;
    unsafe {
        let h = GetStdHandle(STD_OUTPUT_HANDLE);
        if GetConsoleMode(h, &mut mode) == 0 {
            return "GetConsoleMode failed (stdout is not a console handle)".into();
        }
    }
    format!(
        "0x{mode:X}  ENABLE_VIRTUAL_TERMINAL_PROCESSING={}",
        mode & ENABLE_VIRTUAL_TERMINAL_PROCESSING != 0
    )
}
